[package]
name = "newflight"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", features = ["dynamic_linking"] }
nalgebra = "0.33.2"
log = { version = "*", features = ["max_level_warn", "release_max_level_warn"] }
blake3 = "1.8.2"


[profile.dev]
opt-level = 1
